package com.giftech.terbit.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF4A4ECB)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE1E0FF)
val md_theme_light_onPrimaryContainer = Color(0xFF05006D)
val md_theme_light_secondary = Color(0xFF4F56A9)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE0E0FF)
val md_theme_light_onSecondaryContainer = Color(0xFF020865)
val md_theme_light_tertiary = Color(0xFF914278)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD8ED)
val md_theme_light_onTertiaryContainer = Color(0xFF3B002E)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1B0261)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1B0261)
val md_theme_light_surfaceVariant = Color(0xFFE4E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF46464F)
val md_theme_light_outline = Color(0xFF777680)
val md_theme_light_inverseOnSurface = Color(0xFFF4EEFF)
val md_theme_light_inverseSurface = Color(0xFF302175)
val md_theme_light_inversePrimary = Color(0xFFC0C1FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF4A4ECB)
val md_theme_light_outlineVariant = Color(0xFFC7C5D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFC0C1FF)
val md_theme_dark_onPrimary = Color(0xFF14109E)
val md_theme_dark_primaryContainer = Color(0xFF3033B3)
val md_theme_dark_onPrimaryContainer = Color(0xFFE1E0FF)
val md_theme_dark_secondary = Color(0xFFBEC2FF)
val md_theme_dark_onSecondary = Color(0xFF1E2578)
val md_theme_dark_secondaryContainer = Color(0xFF363E90)
val md_theme_dark_onSecondaryContainer = Color(0xFFE0E0FF)
val md_theme_dark_tertiary = Color(0xFFFFADE0)
val md_theme_dark_onTertiary = Color(0xFF591147)
val md_theme_dark_tertiaryContainer = Color(0xFF752A5F)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD8ED)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B0261)
val md_theme_dark_onBackground = Color(0xFFE5DEFF)
val md_theme_dark_surface = Color(0xFF1B0261)
val md_theme_dark_onSurface = Color(0xFFE5DEFF)
val md_theme_dark_surfaceVariant = Color(0xFF46464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C5D0)
val md_theme_dark_outline = Color(0xFF918F9A)
val md_theme_dark_inverseOnSurface = Color(0xFF1B0261)
val md_theme_dark_inverseSurface = Color(0xFFE5DEFF)
val md_theme_dark_inversePrimary = Color(0xFF4A4ECB)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFC0C1FF)
val md_theme_dark_outlineVariant = Color(0xFF46464F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF4A4ECB)
val CustomColor1 = Color(0xFFFFBB00)
val CustomColor2 = Color(0xFF00A650)
val CustomColor3 = Color(0xFFFF0100)
val light_CustomColor1 = Color(0xFF7B5800)
val light_onCustomColor1 = Color(0xFFFFFFFF)
val light_CustomColor1Container = Color(0xFFFFDEA4)
val light_onCustomColor1Container = Color(0xFF261900)
val dark_CustomColor1 = Color(0xFFFFBB00)
val dark_onCustomColor1 = Color(0xFF412D00)
val dark_CustomColor1Container = Color(0xFF5D4200)
val dark_onCustomColor1Container = Color(0xFFFFDEA4)
val light_CustomColor2 = Color(0xFF006D32)
val light_onCustomColor2 = Color(0xFFFFFFFF)
val light_CustomColor2Container = Color(0xFF78FC9B)
val light_onCustomColor2Container = Color(0xFF00210B)
val dark_CustomColor2 = Color(0xFF5ADF81)
val dark_onCustomColor2 = Color(0xFF003917)
val dark_CustomColor2Container = Color(0xFF005224)
val dark_onCustomColor2Container = Color(0xFF78FC9B)
val light_CustomColor3 = Color(0xFFC00100)
val light_onCustomColor3 = Color(0xFFFFFFFF)
val light_CustomColor3Container = Color(0xFFFFDAD4)
val light_onCustomColor3Container = Color(0xFF410000)
val dark_CustomColor3 = Color(0xFFFFB4A8)
val dark_onCustomColor3 = Color(0xFF690100)
val dark_CustomColor3Container = Color(0xFF930100)
val dark_onCustomColor3Container = Color(0xFFFFDAD4)


